/// Liste des pays du monde (noms en français) pour nationalité, pays de résidence, etc.
const List<String> countriesList = [
  'Afghanistan', 'Afrique du Sud', 'Albanie', 'Algérie', 'Allemagne', 'Andorre',
  'Angola', 'Anguilla', 'Antarctique', 'Antigua-et-Barbuda', 'Arabie saoudite',
  'Argentine', 'Arménie', 'Aruba', 'Australie', 'Autriche', 'Azerbaïdjan',
  'Bahamas', 'Bahreïn', 'Bangladesh', 'Barbade', 'Belgique', 'Belize', 'Bénin',
  'Bermudes', 'Bhoutan', 'Biélorussie', 'Bolivie', 'Bosnie-Herzégovine', 'Botswana',
  'Brésil', 'Brunéi Darussalam', 'Bulgarie', 'Burkina Faso', 'Burundi',
  'Cambodge', 'Cameroun', 'Canada', 'Cap-Vert', 'Chili', 'Chine', 'Chypre',
  'Colombie', 'Comores', 'Congo-Brazzaville', 'Congo-Kinshasa', 'Corée du Nord',
  'Corée du Sud', 'Costa Rica', 'Côte d\'Ivoire', 'Croatie', 'Cuba', 'Curaçao',
  'Danemark', 'Djibouti', 'Dominique', 'Égypte', 'Émirats arabes unis', 'Équateur',
  'Érythrée', 'Espagne', 'Estonie', 'Eswatini', 'État de la Cité du Vatican',
  'États fédérés de Micronésie', 'États-Unis', 'Éthiopie', 'Fidji', 'Finlande',
  'France', 'Gabon', 'Gambie', 'Géorgie', 'Ghana', 'Gibraltar', 'Grèce',
  'Grenade', 'Groenland', 'Guadeloupe', 'Guam', 'Guatemala', 'Guernesey',
  'Guinée', 'Guinée équatoriale', 'Guinée-Bissau', 'Guyana', 'Guyane française',
  'Haïti', 'Honduras', 'Hongrie', 'Île de Man', 'Île Norfolk', 'Îles Caïmans',
  'Îles Cook', 'Îles Féroé', 'Îles Marshall', 'Îles Salomon', 'Inde',
  'Indonésie', 'Irak', 'Iran', 'Irlande', 'Islande', 'Israël', 'Italie',
  'Jamaïque', 'Japon', 'Jersey', 'Jordanie', 'Kazakhstan', 'Kenya', 'Kirghizistan',
  'Kiribati', 'Koweït', 'La Réunion', 'Laos', 'Lesotho', 'Lettonie', 'Liban',
  'Libéria', 'Libye', 'Liechtenstein', 'Lituanie', 'Luxembourg', 'Macédoine du Nord',
  'Madagascar', 'Malaisie', 'Malawi', 'Maldives', 'Mali', 'Malte', 'Maroc',
  'Martinique', 'Maurice', 'Mauritanie', 'Mayotte', 'Mexique', 'Moldavie',
  'Monaco', 'Mongolie', 'Monténégro', 'Montserrat', 'Mozambique', 'Myanmar (Birmanie)',
  'Namibie', 'Nauru', 'Népal', 'Nicaragua', 'Niger', 'Nigéria', 'Niue',
  'Norvège', 'Nouvelle-Calédonie', 'Nouvelle-Zélande', 'Oman', 'Ouganda',
  'Ouzbékistan', 'Pakistan', 'Palaos', 'Panama', 'Papouasie-Nouvelle-Guinée',
  'Paraguay', 'Pays-Bas', 'Pérou', 'Philippines', 'Pologne', 'Polynésie française',
  'Porto Rico', 'Portugal', 'Qatar', 'R.A.S. chinoise de Hong Kong', 'R.A.S. chinoise de Macao',
  'République centrafricaine', 'République dominicaine', 'Roumanie', 'Royaume-Uni',
  'Russie', 'Rwanda', 'Sahara occidental', 'Saint-Barthélemy', 'Saint-Christophe-et-Niévès',
  'Saint-Marin', 'Saint-Martin', 'Saint-Pierre-et-Miquelon', 'Saint-Vincent-et-les-Grenadines',
  'Sainte-Hélène', 'Sainte-Lucie', 'Salvador', 'Samoa', 'Samoa américaines',
  'Sao Tomé-et-Principe', 'Sénégal', 'Serbie', 'Seychelles', 'Sierra Leone',
  'Singapour', 'Slovaquie', 'Slovénie', 'Somalie', 'Soudan', 'Soudan du Sud',
  'Sri Lanka', 'Suède', 'Suisse', 'Suriname', 'Syrie', 'Tadjikistan', 'Taïwan',
  'Tanzanie', 'Tchad', 'Tchéquie', 'Territoires palestiniens', 'Thaïlande',
  'Timor oriental', 'Togo', 'Tokelau', 'Tonga', 'Trinité-et-Tobago', 'Tunisie',
  'Turkménistan', 'Turquie', 'Tuvalu', 'Ukraine', 'Uruguay', 'Vanuatu',
  'Venezuela', 'Vietnam', 'Wallis-et-Futuna', 'Yémen', 'Zambie', 'Zimbabwe',
];
